[build]
  command = """npm i -g tsc &&
               npm run build               
               """
  publish = "build/"
  functions = "functions/"
[functions]
  included_files = ["postdata/*.md","static/images/*"]